-- Data from https://data.cms.gov/provider-data/dataset/xubh-q36u (Hospital General Information)
{{ config(materialized='external', location='/tmp/hospital_general_information.parquet') }}
SELECT * FROM read_csv('https://data.payless.health/data.cms.gov%2FHospital_General_Information.csv', 
    header=true, 
    delim=',', 
    dateformat='%m/%d/%Y',
    nullstr='Not Available',
    columns= {
        'Facility ID': 'VARCHAR',
        'Facility Name': 'VARCHAR', 
        'Address': 'VARCHAR',
        'City': 'VARCHAR',
        'State': 'VARCHAR',
        'ZIP Code': 'VARCHAR',
        'County Name': 'VARCHAR',
        'Phone Number': 'VARCHAR',
        'Hospital Type': 'VARCHAR',
        'Hospital Ownership': 'VARCHAR',
        'Emergency Services': 'VARCHAR',
        'Meets criteria for promoting interoperability of EHRs': 'VARCHAR',
        'Hospital overall rating': 'VARCHAR',
        'Hospital overall rating footnote': 'VARCHAR',
        'MORT Group Measure Count': 'INTEGER',
        'Count of Facility MORT Measures': 'INTEGER',
        'Count of MORT Measures Better': 'INTEGER',
        'Count of MORT Measures No Different': 'INTEGER',
        'Count of MORT Measures Worse': 'INTEGER',
        'MORT Group Footnote': 'VARCHAR',
        'Safety Group Measure Count': 'INTEGER',
        'Count of Facility Safety Measures': 'INTEGER',
        'Count of Safety Measures Better': 'INTEGER',
        'Count of Safety Measures No Different': 'INTEGER',
        'Count of Safety Measures Worse': 'INTEGER',
        'Safety Group Footnote': 'VARCHAR',
        'READM Group Measure Count': 'INTEGER',
        'Count of Facility READM Measures': 'INTEGER',
        'Count of READM Measures Better': 'INTEGER',
        'Count of READM Measures No Different': 'INTEGER', 
        'Count of READM Measures Worse': 'INTEGER',
        'READM Group Footnote': 'VARCHAR',
        'Pt Exp Group Measure Count': 'INTEGER',
        'Count of Facility Pt Exp Measures': 'INTEGER',
        'Pt Exp Group Footnote': 'VARCHAR',
        'TE Group Measure Count': 'INTEGER',
        'Count of Facility TE Measures': 'INTEGER',
        'TE Group Footnote': 'VARCHAR'
    }
)