-- Data from https://download.cms.gov/nppes/NPPES_Data_Dissemination_July_2023.zip
-- Via https://www.cms.gov/Regulations-and-Guidance/Administrative-Simplification/NationalProvIdentStand/DataDissemination
-- 
{{ config(materialized='external', location='/tmp/national_plan_and_provider_identifiers.parquet') }}
SELECT *
FROM read_csv('/Users/me/dropbox/projects/data_build_tool_payless.health/npidata_pfile_20050523-20230709.csv', 
  header=True,
  delim=',',
  quote='"',
  nullstr='',
  dateformat='%m/%d/%Y',
  parallel=false,
  columns={
    'NPI': 'BIGINT',
    'Entity Type Code': 'VARCHAR',
    'Replacement NPI': 'BIGINT', 
    'Employer Identification Number (EIN)': 'VARCHAR',
    'Provider Organization Name (Legal Business Name)': 'VARCHAR',
    'Provider Last Name (Legal Name)': 'VARCHAR',
    'Provider First Name': 'VARCHAR',
    'Provider Middle Name': 'VARCHAR',
    'Provider Name Prefix Text': 'VARCHAR',
    'Provider Name Suffix Text': 'VARCHAR',
    'Provider Credential Text': 'VARCHAR',
    'Provider Other Organization Name': 'VARCHAR',
    'Provider Other Organization Name Type Code': 'VARCHAR',
    'Provider Other Last Name': 'VARCHAR',
    'Provider Other First Name': 'VARCHAR',
    'Provider Other Middle Name': 'VARCHAR',
    'Provider Other Name Prefix Text': 'VARCHAR',
    'Provider Other Name Suffix Text': 'VARCHAR',
    'Provider Other Credential Text': 'VARCHAR',
    'Provider Other Last Name Type Code': 'INT',
    'Provider First Line Business Mailing Address': 'VARCHAR',
    'Provider Second Line Business Mailing Address': 'VARCHAR',
    'Provider Business Mailing Address City Name': 'VARCHAR',
    'Provider Business Mailing Address State Name': 'VARCHAR',
    'Provider Business Mailing Address Postal Code': 'VARCHAR',
    'Provider Business Mailing Address Country Code (If outside U.S.)': 'VARCHAR',
    'Provider Business Mailing Address Telephone Number': 'VARCHAR',
    'Provider Business Mailing Address Fax Number': 'VARCHAR',
    'Provider First Line Business Practice Location Address': 'VARCHAR',
    'Provider Second Line Business Practice Location Address': 'VARCHAR',
    'Provider Business Practice Location Address City Name': 'VARCHAR',
    'Provider Business Practice Location Address State Name': 'VARCHAR',
    'Provider Business Practice Location Address Postal Code': 'VARCHAR',
    'Provider Business Practice Location Address Country Code (If outside U.S.)': 'VARCHAR',
    'Provider Business Practice Location Address Telephone Number': 'VARCHAR',
    'Provider Business Practice Location Address Fax Number': 'VARCHAR',
    'Provider Enumeration Date': 'VARCHAR',
    'Last Update Date': 'VARCHAR',
    'NPI Deactivation Reason Code': 'VARCHAR',
    'NPI Deactivation Date': 'VARCHAR',
    'NPI Reactivation Date': 'VARCHAR',
    'Provider Gender Code': 'VARCHAR', 
    'Authorized Official Last Name': 'VARCHAR',
    'Authorized Official First Name': 'VARCHAR',
    'Authorized Official Middle Name': 'VARCHAR',
    'Authorized Official Title or Position': 'VARCHAR',
    'Authorized Official Telephone Number': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_1': 'VARCHAR',
    'Provider License Number_1': 'VARCHAR',
    'Provider License Number State Code_1': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_1': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_2': 'VARCHAR',
    'Provider License Number_2': 'VARCHAR',
    'Provider License Number State Code_2': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_2': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_3': 'VARCHAR',
    'Provider License Number_3': 'VARCHAR',
    'Provider License Number State Code_3': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_3': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_4': 'VARCHAR',
    'Provider License Number_4': 'VARCHAR',
    'Provider License Number State Code_4': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_4': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_5': 'VARCHAR',
    'Provider License Number_5': 'VARCHAR',
    'Provider License Number State Code_5': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_5': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_6': 'VARCHAR',
    'Provider License Number_6': 'VARCHAR',
    'Provider License Number State Code_6': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_6': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_7': 'VARCHAR',
    'Provider License Number_7': 'VARCHAR',
    'Provider License Number State Code_7': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_7': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_8': 'VARCHAR',
    'Provider License Number_8': 'VARCHAR',
    'Provider License Number State Code_8': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_8': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_9': 'VARCHAR',
    'Provider License Number_9': 'VARCHAR',
    'Provider License Number State Code_9': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_9': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_10': 'VARCHAR',
    'Provider License Number_10': 'VARCHAR',
    'Provider License Number State Code_10': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_10': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_11': 'VARCHAR',
    'Provider License Number_11': 'VARCHAR',
    'Provider License Number State Code_11': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_11': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_12': 'VARCHAR',
    'Provider License Number_12': 'VARCHAR',
    'Provider License Number State Code_12': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_12': 'VARCHAR',
    'Healthcare Provider Taxonomy Code_13': 'VARCHAR',
    'Provider License Number_13': 'VARCHAR',
    'Provider License Number State Code_13': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_13': 'VARCHAR',   
    'Healthcare Provider Taxonomy Code_14': 'VARCHAR',
    'Provider License Number_14': 'VARCHAR',
    'Provider License Number State Code_14': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_14': 'VARCHAR',  
    'Healthcare Provider Taxonomy Code_15': 'VARCHAR',
    'Provider License Number_15': 'VARCHAR',
    'Provider License Number State Code_15': 'VARCHAR',
    'Healthcare Provider Primary Taxonomy Switch_15': 'VARCHAR',
    'Other Provider Identifier_1': 'VARCHAR',
    'Other Provider Identifier Type Code_1': 'VARCHAR',
    'Other Provider Identifier State_1': 'VARCHAR',
    'Other Provider Identifier Issuer_1': 'VARCHAR',
    'Other Provider Identifier_2': 'VARCHAR',
    'Other Provider Identifier Type Code_2': 'VARCHAR',
    'Other Provider Identifier State_2': 'VARCHAR',
    'Other Provider Identifier Issuer_2': 'VARCHAR',
    'Other Provider Identifier_3': 'VARCHAR',
    'Other Provider Identifier Type Code_3': 'VARCHAR',
    'Other Provider Identifier State_3': 'VARCHAR',
    'Other Provider Identifier Issuer_3': 'VARCHAR',
    'Other Provider Identifier_4': 'VARCHAR',
    'Other Provider Identifier Type Code_4': 'VARCHAR',
    'Other Provider Identifier State_4': 'VARCHAR',
    'Other Provider Identifier Issuer_4': 'VARCHAR',
    'Other Provider Identifier_5': 'VARCHAR',
    'Other Provider Identifier Type Code_5': 'VARCHAR',
    'Other Provider Identifier State_5': 'VARCHAR',
    'Other Provider Identifier Issuer_5': 'VARCHAR',
    'Other Provider Identifier_6': 'VARCHAR',
    'Other Provider Identifier Type Code_6': 'VARCHAR',
    'Other Provider Identifier State_6': 'VARCHAR',
    'Other Provider Identifier Issuer_6': 'VARCHAR',
    'Other Provider Identifier_7': 'VARCHAR',
    'Other Provider Identifier Type Code_7': 'VARCHAR',
    'Other Provider Identifier State_7': 'VARCHAR',
    'Other Provider Identifier Issuer_7': 'VARCHAR',
    'Other Provider Identifier_8': 'VARCHAR',
    'Other Provider Identifier Type Code_8': 'VARCHAR',
    'Other Provider Identifier State_8': 'VARCHAR',
    'Other Provider Identifier Issuer_8': 'VARCHAR',
    'Other Provider Identifier_9': 'VARCHAR',
    'Other Provider Identifier Type Code_9': 'VARCHAR',
    'Other Provider Identifier State_9': 'VARCHAR',
    'Other Provider Identifier Issuer_9': 'VARCHAR',
    'Other Provider Identifier_10': 'VARCHAR',
    'Other Provider Identifier Type Code_10': 'VARCHAR',
    'Other Provider Identifier State_10': 'VARCHAR',
    'Other Provider Identifier Issuer_10': 'VARCHAR',
    'Other Provider Identifier_11': 'VARCHAR',
    'Other Provider Identifier Type Code_11': 'VARCHAR',
    'Other Provider Identifier State_11': 'VARCHAR',
    'Other Provider Identifier Issuer_11': 'VARCHAR',
    'Other Provider Identifier_12': 'VARCHAR',
    'Other Provider Identifier Type Code_12': 'VARCHAR',
    'Other Provider Identifier State_12': 'VARCHAR',
    'Other Provider Identifier Issuer_12': 'VARCHAR',
    'Other Provider Identifier_13': 'VARCHAR',
    'Other Provider Identifier Type Code_13': 'VARCHAR',
    'Other Provider Identifier State_13': 'VARCHAR',
    'Other Provider Identifier Issuer_13': 'VARCHAR',
    'Other Provider Identifier_14': 'VARCHAR',
    'Other Provider Identifier Type Code_14': 'VARCHAR', 
    'Other Provider Identifier State_14': 'VARCHAR',
    'Other Provider Identifier Issuer_14': 'VARCHAR',
    'Other Provider Identifier_15': 'VARCHAR',
    'Other Provider Identifier Type Code_15': 'VARCHAR',
    'Other Provider Identifier State_15': 'VARCHAR',
    'Other Provider Identifier Issuer_15': 'VARCHAR',
    'Other Provider Identifier_16': 'VARCHAR',
    'Other Provider Identifier Type Code_16': 'VARCHAR',
    'Other Provider Identifier State_16': 'VARCHAR',
    'Other Provider Identifier Issuer_16': 'VARCHAR',
    'Other Provider Identifier_17': 'VARCHAR',
    'Other Provider Identifier Type Code_17': 'VARCHAR',
    'Other Provider Identifier State_17': 'VARCHAR',
    'Other Provider Identifier Issuer_17': 'VARCHAR',
    'Other Provider Identifier_18': 'VARCHAR',
    'Other Provider Identifier Type Code_18': 'VARCHAR',
    'Other Provider Identifier State_18': 'VARCHAR',
    'Other Provider Identifier Issuer_18': 'VARCHAR',
    'Other Provider Identifier_19': 'VARCHAR',
    'Other Provider Identifier Type Code_19': 'VARCHAR',
    'Other Provider Identifier State_19': 'VARCHAR',
    'Other Provider Identifier Issuer_19': 'VARCHAR',
    'Other Provider Identifier_20': 'VARCHAR',
    'Other Provider Identifier Type Code_20': 'VARCHAR',
    'Other Provider Identifier State_20': 'VARCHAR',
    'Other Provider Identifier Issuer_20': 'VARCHAR',
    'Other Provider Identifier_21': 'VARCHAR',
    'Other Provider Identifier Type Code_21': 'VARCHAR',
    'Other Provider Identifier State_21': 'VARCHAR',
    'Other Provider Identifier Issuer_21': 'VARCHAR',
    'Other Provider Identifier_22': 'VARCHAR',
    'Other Provider Identifier Type Code_22': 'VARCHAR',
    'Other Provider Identifier State_22': 'VARCHAR',
    'Other Provider Identifier Issuer_22': 'VARCHAR',
    'Other Provider Identifier_23': 'VARCHAR',
    'Other Provider Identifier Type Code_23': 'VARCHAR',
    'Other Provider Identifier State_23': 'VARCHAR',
    'Other Provider Identifier Issuer_23': 'VARCHAR',
    'Other Provider Identifier_24': 'VARCHAR',  
    'Other Provider Identifier Type Code_24': 'VARCHAR',
    'Other Provider Identifier State_24': 'VARCHAR',
    'Other Provider Identifier Issuer_24': 'VARCHAR',
    'Other Provider Identifier_25': 'VARCHAR',
    'Other Provider Identifier Type Code_25': 'VARCHAR',
    'Other Provider Identifier State_25': 'VARCHAR',
    'Other Provider Identifier Issuer_25': 'VARCHAR',
    'Other Provider Identifier_26': 'VARCHAR',
    'Other Provider Identifier Type Code_26': 'VARCHAR',
    'Other Provider Identifier State_26': 'VARCHAR',
    'Other Provider Identifier Issuer_26': 'VARCHAR',
    'Other Provider Identifier_27': 'VARCHAR',
    'Other Provider Identifier Type Code_27': 'VARCHAR',
    'Other Provider Identifier State_27': 'VARCHAR',
    'Other Provider Identifier Issuer_27': 'VARCHAR',
    'Other Provider Identifier_28': 'VARCHAR',
    'Other Provider Identifier Type Code_28': 'VARCHAR',
    'Other Provider Identifier State_28': 'VARCHAR',
    'Other Provider Identifier Issuer_28': 'VARCHAR',
    'Other Provider Identifier_29': 'VARCHAR',
    'Other Provider Identifier Type Code_29': 'VARCHAR',
    'Other Provider Identifier State_29': 'VARCHAR',
    'Other Provider Identifier Issuer_29': 'VARCHAR',
    'Other Provider Identifier_30': 'VARCHAR',
    'Other Provider Identifier Type Code_30': 'VARCHAR',
    'Other Provider Identifier State_30': 'VARCHAR',
    'Other Provider Identifier Issuer_30': 'VARCHAR',
    'Other Provider Identifier_31': 'VARCHAR',
    'Other Provider Identifier Type Code_31': 'VARCHAR',
    'Other Provider Identifier State_31': 'VARCHAR',
    'Other Provider Identifier Issuer_31': 'VARCHAR',
    'Other Provider Identifier_32': 'VARCHAR',
    'Other Provider Identifier Type Code_32': 'VARCHAR',
    'Other Provider Identifier State_32': 'VARCHAR',
    'Other Provider Identifier Issuer_32': 'VARCHAR',
    'Other Provider Identifier_33': 'VARCHAR',
    'Other Provider Identifier Type Code_33': 'VARCHAR',
    'Other Provider Identifier State_33': 'VARCHAR',
    'Other Provider Identifier Issuer_33': 'VARCHAR',
    'Other Provider Identifier_34': 'VARCHAR',
    'Other Provider Identifier Type Code_34': 'VARCHAR',
    'Other Provider Identifier State_34': 'VARCHAR',
    'Other Provider Identifier Issuer_34': 'VARCHAR',
    'Other Provider Identifier_35': 'VARCHAR',
    'Other Provider Identifier Type Code_35': 'VARCHAR',
    'Other Provider Identifier State_35': 'VARCHAR',
    'Other Provider Identifier Issuer_35': 'VARCHAR',
    'Other Provider Identifier_36': 'VARCHAR',
    'Other Provider Identifier Type Code_36': 'VARCHAR',
    'Other Provider Identifier State_36': 'VARCHAR',
    'Other Provider Identifier Issuer_36': 'VARCHAR',
    'Other Provider Identifier_37': 'VARCHAR',
    'Other Provider Identifier Type Code_37': 'VARCHAR',
    'Other Provider Identifier State_37': 'VARCHAR',
    'Other Provider Identifier Issuer_37': 'VARCHAR',
    'Other Provider Identifier_38': 'VARCHAR',
    'Other Provider Identifier Type Code_38': 'VARCHAR',
    'Other Provider Identifier State_38': 'VARCHAR',
    'Other Provider Identifier Issuer_38': 'VARCHAR',
    'Other Provider Identifier_39': 'VARCHAR',
    'Other Provider Identifier Type Code_39': 'VARCHAR',
    'Other Provider Identifier State_39': 'VARCHAR',
    'Other Provider Identifier Issuer_39': 'VARCHAR',
    'Other Provider Identifier_40': 'VARCHAR',
    'Other Provider Identifier Type Code_40': 'VARCHAR',
    'Other Provider Identifier State_40': 'VARCHAR',
    'Other Provider Identifier Issuer_40': 'VARCHAR',
    'Other Provider Identifier_41': 'VARCHAR',
    'Other Provider Identifier Type Code_41': 'VARCHAR',
    'Other Provider Identifier State_41': 'VARCHAR',
    'Other Provider Identifier Issuer_41': 'VARCHAR',
    'Other Provider Identifier_42': 'VARCHAR',
    'Other Provider Identifier Type Code_42': 'VARCHAR',
    'Other Provider Identifier State_42': 'VARCHAR',
    'Other Provider Identifier Issuer_42': 'VARCHAR',
    'Other Provider Identifier_43': 'VARCHAR',
    'Other Provider Identifier Type Code_43': 'VARCHAR',
    'Other Provider Identifier State_43': 'VARCHAR',
    'Other Provider Identifier Issuer_43': 'VARCHAR',
    'Other Provider Identifier_44': 'VARCHAR',
    'Other Provider Identifier Type Code_44': 'VARCHAR',
    'Other Provider Identifier State_44': 'VARCHAR',
    'Other Provider Identifier Issuer_44': 'VARCHAR',
    'Other Provider Identifier_45': 'VARCHAR',
    'Other Provider Identifier Type Code_45': 'VARCHAR',
    'Other Provider Identifier State_45': 'VARCHAR',
    'Other Provider Identifier Issuer_45': 'VARCHAR',
    'Other Provider Identifier_46': 'VARCHAR',
    'Other Provider Identifier Type Code_46': 'VARCHAR',
    'Other Provider Identifier State_46': 'VARCHAR',
    'Other Provider Identifier Issuer_46': 'VARCHAR',
    'Other Provider Identifier_47': 'VARCHAR',
    'Other Provider Identifier Type Code_47': 'VARCHAR',
    'Other Provider Identifier State_47': 'VARCHAR',
    'Other Provider Identifier Issuer_47': 'VARCHAR',
    'Other Provider Identifier_48': 'VARCHAR',
    'Other Provider Identifier Type Code_48': 'VARCHAR',
    'Other Provider Identifier State_48': 'VARCHAR',
    'Other Provider Identifier Issuer_48': 'VARCHAR',
    'Other Provider Identifier_49': 'VARCHAR',
    'Other Provider Identifier Type Code_49': 'VARCHAR',
    'Other Provider Identifier State_49': 'VARCHAR',
    'Other Provider Identifier Issuer_49': 'VARCHAR',  
    'Other Provider Identifier_50': 'VARCHAR',
    'Other Provider Identifier Type Code_50': 'VARCHAR',
    'Other Provider Identifier State_50': 'VARCHAR',
    'Other Provider Identifier Issuer_50': 'VARCHAR',
    'Is Sole Proprietor': 'VARCHAR',
    'Is Organization Subpart': 'VARCHAR', 
    'Parent Organization LBN': 'VARCHAR',
    'Parent Organization TIN': 'VARCHAR',
    'Authorized Official Name Prefix Text': 'VARCHAR',
    'Authorized Official Name Suffix Text': 'VARCHAR',
    'Authorized Official Credential Text': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_1': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_2': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_3': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_4': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_5': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_6': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_7': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_8': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_9': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_10': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_11': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_12': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_13': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_14': 'VARCHAR',
    'Healthcare Provider Taxonomy Group_15': 'VARCHAR',
    'Certification Date': 'VARCHAR'
  }
)